### ISSUE TITLE
makeotf error

### ISSUE THREAD

**Issue by maplelover** [adobe-fonts/source-han-sans#189]
https://github.com/adobe-fonts/source-han-sans/blob/master/COMMANDS.txt

--------------------

makeotf -f cidfont.ps.CN -ff features.CN -fi cidfontinfo.CN -mf ../FontMenuNameDB.SUBSET -r -nS -cs 25 -ch ../UniSourceHanSansCN-UTF32-H

makeotf [Warning] Could not find an Adobe CMAP Mac encoding mapping file. If you want a Mac cmap subtable, please specify the Mac CMAP encoding file with the '-cm' option.
makeotf [Warning] Could not find a Unicode Variation Sequence file in the appropriate FDK/Tools/SharedData/Adobe Cmaps/ subdirectory.
makeotf [Note] setting the USE_TYPO_METRICS OS/2 fsSelection bit 7 from fontinfo keyword.
makeotf [Note] setting the WEIGHT_WIDTH_SLOPE_ONLY OS/2 fsSelection bit 8 from fontinfo keyword.
makeotf [Note] setting the OBLIQUE OS/2 fsSelection bit 9 from fontinfo keyword.
/Users/me/bin/FDK/Tools/osx/Python/Current/lib/python2.7/genericpath.py:79: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  s1 = min(m)
Traceback (most recent call last):
  File "/Users/me/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 2593, in <module>
    main()
  File "/Users/me/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 2587, in main
    saveOptionsFile(makeOTFParams) # this always saves options to kDefaultOptionsFile; may also save to user-specified option file.
  File "/Users/me/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 546, in saveOptionsFile
    writeOptionsFile(makeOTFParams, filePath)
  File "/Users/me/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 524, in writeOptionsFile
    relativeDirPath = getRelativeDirPath(fileDir, fprDir)
  File "/Users/me/bin/FDK/Tools/osx/../SharedData/FDKScripts/MakeOTF.py", line 722, in getRelativeDirPath
    relPath = os.path.relpath(absPath1, abspath2)
  File "/Users/me/bin/FDK/Tools/osx/Python/Current/lib/python2.7/posixpath.py", line 434, in relpath
    i = len(commonprefix([start_list, path_list]))
  File "/Users/me/bin/FDK/Tools/osx/Python/Current/lib/python2.7/genericpath.py", line 79, in commonprefix
    s1 = min(m)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)

How can I fix it?
Thank you.

**Comment by kenlunde** [comment]
Using the Terminal app, please navigate to the directory in which you executed that command line, enter _pwd_, then post the result here.

**Comment by maplelover** [comment]
The font path does contain Chinese characters. The problem was fixed. Thanks for your reply.

**Comment by kenlunde** [comment]
@maplelover That is precisely what I was getting at with my question.

**Comment by readroberts** [comment]
This is definitely an important bug, and will be fixed soon.
